
name: 'Portfolio Pessoal - CI'

on: 
  workflow_dispatch:
  push:
    branches:
      - main

jobs: 
  tests:
    runs-on: ubuntu-latest

    env:
      API_BASE_URL: 'http://localhost:3333'
      
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Instalar deps
        run: npm install
        
      - name: Instalar o servidor da aplicação
        run: npm start &

      - name: Executar os testes
        run: npm test
             
